# Стадия сборки
FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline || mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests -X -e -B

# Стадия запуска
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
RUN apk add --no-cache bash netcat-openbsd
# Копируем скрипт из текущей папки
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh
# Копируем JAR
COPY --from=build /app/target/payment-app.jar app.jar
EXPOSE 8081
ENTRYPOINT ["/wait-for-it.sh", "postgres:5432", "--", "java", "-jar", "app.jar"]