spring:
  datasource:
    legal:
      jdbc-url: jdbc:postgresql://host.docker.internal:5433/payment_system_legal
      username: LdKrlv
      password: 0987765
      driver-class-name: org.postgresql.Driver
    individual:
      jdbc-url: jdbc:postgresql://host.docker.internal:5432/payment_system_individual
      username: LdKrlv
      password: 0987765
      driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false

  artemis:
    host: artemis
    port: 61616
    user: artemis
    password: simetraehcapa
    mode: native
    #    broker-url: "tcp://payment_artemis:61616?reconnectAttempts=-1"
    broker-url: ${SPRING_ARTEMIS_BROKER_URL:tcp://localhost:61616?reconnectAttempts=-1}

  #  logging:
  #    level:
  #      org.springframework.jms: DEBUG

  # >>> ДОБАВИТЬ: Kafka-конфиг
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    #    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:host.docker.internal:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: payment-processing
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    admin:
      properties:
        bootstrap.servers: localhost:9092

  graphql:
    path: /graphql
    graphiql:
      enabled: true

  logging:
    level:
      org.springframework.jms: DEBUG
      # >>> (не обязательно, но полезно) добавь логирование Kafka:
      org.springframework.kafka: INFO

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8080
#  поменяли с 8080 при добавлении tyk на 8080

# Свои флаги (по умолчанию всё выкл)
app:
  liquibase:
    enabled: true
    legal-enabled: true
    individual-enabled: true

  messaging:
    backend: kafka