version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    container_name: 2nd_DB
    environment:
      POSTGRES_USER: LdKrlv
      POSTGRES_PASSWORD: 0987765
      POSTGRES_DB: Payment_system_prototype
    ports:
      - "5433:5432"
    volumes:
      - payment_system_prototype_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U LdKrlv -d Payment_system_prototype" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - payment_network

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: 2nd_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ladkirillova@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 0987765
    ports:
      - "0.0.0.0:8081:80"
    depends_on:
      - postgres
    networks:
      - payment_network


  payment-app:
    build: ./Payment_System
    ports:
      - "8083:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Payment_system_prototype
      SPRING_DATASOURCE_USERNAME: LdKrlv
      SPRING_DATASOURCE_PASSWORD: 0987765
      SPRING_LIQUIBASE_ENABLED: "true"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - payment_network

volumes:
  payment_system_prototype_data:
    driver: local

networks:
  payment_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16